### ISSUE TITLE
isInCategoryLookup() loop error.

### ISSUE THREAD

**Issue by Alexia** [oOeyes/TippingOver#3]
If the $id passed into isInCategoryLookup() is a string the loop will continue to +1 until it errors out returning false.  Seems like this function should be casting $id to an integer before running the loop.

https://github.com/oOeyes/TippingOver/blob/135e5a61caa2d87e0f42fcc4584dbfe7bec2ee7a/includes/WikiTooltips.php#L248

**Comment by oOeyes** [comment]
The extra defensiveness doesn't hurt, so I've made the change and re-released the 0.53 version.

The upside is this issue doesn't materially affect any current version as it is only called in one location with an id supplied by Title::getArticleID, so I'm going to label it an enhancement since is more safety for future updates.
